AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/*
    - config/initializers/devise.rb
    - config/environments/development.rb
    - config/application.rb
    - app/helpers/application_helper.rb
    - lib/tasks/resque.rb
    - db/schema.rb
