default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prophetratings_development

test:
  <<: *default
  database: prophetratings_test

production:
  <<: *default
  database: prophetratings_production
  username: prophetratings
  password: <%= ENV["PROPHETRATINGS_DATABASE_PASSWORD"] %>
